# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BackgroundSwitcher
                                 A QGIS plugin
 Simple toolbar dropdown that enables quick switching of the map canvas background colour.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-11
        copyright            : (C) 2024 by Laidlaw
        email                : laidlaw@duck.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BackgroundSwitcher class from file BackgroundSwitcher.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .background_switcher import BackgroundSwitcher
    return BackgroundSwitcher(iface)
